site_name: mic-toolkit
site_url: https://micvitc.github.io/mic-toolkit/
nav:
    - Home: index.md
    - Synthetic: synthetic.md
    - Contributing: contributing.md
repo_url: https://github.com/micvitc/mic-toolkit
repo_name: micvitc/mic-toolkit

theme:
    name: material
    features:
        - content.code.copy
        - content.code.select
    palette:
        primary: black
        accent: indigo
    version:
        provider: pip
        package: mic-toolkit
plugins:
    - mkdocstrings
    - social:
        enabled: !ENV [CI, false]
        cards: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences




